// ============================================================================
// Module: iis_slave_rx
// Description: IIS (I2S Philips Standard) Slave Receiver
//   - Receives audio data from external ADC/Codec in slave mode
//   - BCLK and LRCLK are inputs (driven by master/codec)
//   - SDIN is serial data input
//   - Outputs 24-bit left/right channel data with valid strobes
//
// Timing (I2S Philips Standard):
//   - Data valid on BCLK rising edge (receiver samples on rising edge)
//   - MSB delayed by 1 BCLK after LRCLK transition
//   - For 48kHz fs with 64x BCLK: each channel gets 32 BCLK slots
//   - LRCLK = 0 => Left channel, LRCLK = 1 => Right channel
//
// Parameters:
//   - DATA_WIDTH    : Audio sample width (default 24)
//   - BCLK_DIV      : BCLK cycles per LRCLK half-period (default 32 for 64x mode)
//
// Clock Domain: bclk
// ============================================================================

module iis_slave_rx #(
    parameter DATA_WIDTH  = 24,
    parameter BCLK_DIV    = 32          // 32 BCLK per channel (64 BCLK per LRCLK period)
) (
    input  wire                     rst_n,      // Async reset, active low
    input  wire                     bclk,       // IIS bit clock (3.072MHz for 48kHz×64)
    input  wire                     lrclk,      // IIS word select / LR clock (48kHz)
    input  wire                     sdin,       // IIS serial data input
    output reg  [DATA_WIDTH-1:0]    l_data,     // Left channel parallel data
    output reg  [DATA_WIDTH-1:0]    r_data,     // Right channel parallel data
    output reg                      l_valid,    // Left data valid (1 bclk pulse)
    output reg                      r_valid     // Right data valid (1 bclk pulse)
);

    // ========================================================================
    // IIS Protocol State Machine
    //
    // I2S Timing Diagram (Philips Standard):
    //
    // BCLK:  _/‾\_/‾\_/‾\_/‾\_/‾\_/‾\_/‾\_..._/‾\_/‾\_
    // LRCLK: ________/‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾\________
    // SDIN:   ...  X MSB B22 B21 ... B0 LSB  X  X MSB ...
    //
    // LRCLK changes near BCLK falling edge (transmitter side).
    // On the next BCLK rising edge, MSB of the new channel is valid.
    // ========================================================================

    // LRCLK edge detection (1-stage delay)
    //   LRCLK is generated by FPGA in the same bclk domain — no metastability
    //   concern. 1-stage delay (not 2) is REQUIRED for correct I2S MSB capture:
    //   FPGA changes LRCLK at posedge N → PCM1808 sees it at posedge N+1
    //   (setup-time delay) → MSB valid at posedge N+2 (I2S 1-BCLK delay).
    //   1-stage sync detects edge at N+1, first capture at N+2 = MSB. ✓
    //   2-stage sync would detect at N+2, capture at N+3 = bit22. ✗
    reg lrclk_d1;
    wire lrclk_edge;

    // Bit counter: 0 to BCLK_DIV-1 for each channel
    // BCLK_DIV=32 → 需要 5 位 (0~31)
    localparam BCNT_WIDTH = (BCLK_DIV <= 2)  ? 1 :
                            (BCLK_DIV <= 4)  ? 2 :
                            (BCLK_DIV <= 8)  ? 3 :
                            (BCLK_DIV <= 16) ? 4 :
                            (BCLK_DIV <= 32) ? 5 : 6;
    reg [BCNT_WIDTH-1:0] bit_cnt;

    // Shift register for incoming serial data
    reg [DATA_WIDTH-1:0] shift_reg;

    // Current channel (from latched LRCLK at edge detection)
    reg current_channel;  // 0=Left, 1=Right

    // ========================================================================
    // LRCLK edge detection
    // ========================================================================
    always @(posedge bclk or negedge rst_n) begin
        if (!rst_n) begin
            lrclk_d1 <= 1'b0;
        end else begin
            lrclk_d1 <= lrclk;
        end
    end

    // Rising or falling edge of LRCLK indicates channel boundary
    assign lrclk_edge = lrclk ^ lrclk_d1;

    // ========================================================================
    // Bit counter & shift register
    // ========================================================================
    always @(posedge bclk or negedge rst_n) begin
        if (!rst_n) begin
            bit_cnt        <= 0;
            shift_reg      <= 0;
            l_data         <= 0;
            r_data         <= 0;
            l_valid        <= 1'b0;
            r_valid        <= 1'b0;
            current_channel <= 1'b0;
        end else begin
            // Default: de-assert valid strobes (pulse for 1 cycle)
            l_valid <= 1'b0;
            r_valid <= 1'b0;

            if (lrclk_edge) begin
                // ============================================================
                // LRCLK edge detected → latch previous word, start new channel
                // I2S spec: MSB delayed by 1 BCLK after LRCLK transition,
                // so bit_cnt=0 is the skip cycle (no capture)
                // ============================================================

                // Latch the completed word
                if (lrclk_d1 == 1'b0) begin
                    l_data  <= shift_reg;
                    l_valid <= 1'b1;
                end else begin
                    r_data  <= shift_reg;
                    r_valid <= 1'b1;
                end

                current_channel <= lrclk;
                bit_cnt   <= 1;      // skip bit_cnt=0 (I2S MSB delay)

            end else if (bit_cnt == BCLK_DIV - 1) begin
                // ============================================================
                // Fallback: End of channel slot (bit_cnt == 31 for 64x mode)
                // ============================================================

                if (current_channel == 1'b0) begin
                    l_data  <= shift_reg;
                    l_valid <= 1'b1;
                end else begin
                    r_data  <= shift_reg;
                    r_valid <= 1'b1;
                end

                bit_cnt <= 0;
                current_channel <= ~current_channel;
                // bit_cnt=0 → skip (MSB delayed), next cycle bit_cnt=1 captures MSB

            end else if (bit_cnt >= 1 && bit_cnt <= DATA_WIDTH) begin
                // ============================================================
                // Capture data: bit_cnt=1→MSB[23], 2→B22[22], ..., 24→B0[0]
                // ============================================================
                shift_reg[DATA_WIDTH - bit_cnt] <= sdin;
                bit_cnt <= bit_cnt + 1'b1;

            end else begin
                // bit_cnt=0 (skip) or bit_cnt>DATA_WIDTH (trailing zeros): just count
                bit_cnt <= bit_cnt + 1'b1;
            end
        end
    end

endmodule
